name: core

publish_to: core

version: 0.0.1

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  rxdart: ^0.26.0
  intl: ^0.17.0
  uuid: ^3.0.6
  fancy_stream: ^4.0.0+14
  diacritic: ^0.1.3
  string_mask: ^1.0.0
  brasil_fields: ^1.4.2
  loading_animation_widget: ^1.1.0+5
  date_time_picker: ^2.1.0
  flutter_svg_provider: ^1.0.3
  multiple_result: ^3.1.0
  shared_preferences: ^2.0.6
  lottie: ^2.0.0
  circle_nav_bar: ^2.0.1+1
  flutter_switch: ^0.3.2
  scroll_date_picker: ^3.6.0
  pinput: ^2.2.31

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
   